name: Build Hugo - WITH CACHE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code from https://github.com/gohugoio/hugo.git
        uses: actions/checkout@v4.1.1
        with:
          repository: gohugoio/hugo
          ref: stable

      - name: Setup the cache after checkout to build a cache key using go.sum
        uses: actions/cache@3.3.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Setup go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21.6'

      - name: Build the hugo executable
        run: go install --tags extended

      - uses: actions/upload-artifact@v2
        with:
          name: hugo
          path: /home/runner/go/bin/hugo
